"""empty message

Revision ID: 81ea5849f330
Revises: b9bbdd796121
Create Date: 2020-05-15 18:03:14.053806

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81ea5849f330'
down_revision = 'b9bbdd796121'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('noticias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('link', sa.String(), nullable=True),
    sa.Column('titulo', sa.String(), nullable=True),
    sa.Column('data', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('link')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('noticias')
    # ### end Alembic commands ###
